[build]
  command = "npm ci && npm run build"   # install fresh & build
  publish = "out"                        # Next.js static export folder

[plugins]
  # disable any Gatsby plugin
  [[plugins]]
    package = "@netlify/plugin-nextjs"
